# Generated by Django 3.0 on 2021-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoestoque',
            options={'verbose_name': 'Produto Estoque', 'verbose_name_plural': 'produtos estoque'},
        ),
        migrations.AlterField(
            model_name='produtoestoque',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterModelTable(
            name='produtoestoque',
            table='produtoestoque',
        ),
    ]
