# Generated by Django 3.0 on 2021-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210405_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoestoque',
            options={'verbose_name': 'Produto Estoque', 'verbose_name_plural': 'Produtos Estoque'},
        ),
        migrations.AlterField(
            model_name='produtoestoque',
            name='quantidade',
            field=models.FloatField(default=0, verbose_name='Quantidade'),
        ),
    ]
