# Generated by Django 3.0 on 2021-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, max_length=50, verbose_name='Data de Cadastro'),
        ),
    ]
