# Generated by Django 3.0 on 2021-04-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_auto_20210405_1149'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_movimentacao', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída')], max_length=50, verbose_name='Movimentação')),
                ('data', models.DateField(max_length=50, verbose_name='Data Movimentação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Empresa', verbose_name='Empresa')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Gerente', verbose_name='Gerente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Vendedor', verbose_name='Vendedor')),
            ],
        ),
    ]
