# Generated by Django 3.0 on 2021-04-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'movimentações'},
        ),
        migrations.AlterModelOptions(
            name='produtomovimentacao',
            options={'verbose_name': 'Movimentação do Produto', 'verbose_name_plural': 'Movimentações dos Produtos'},
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table='movimentacao',
        ),
        migrations.AlterModelTable(
            name='produtomovimentacao',
            table='produtomovimentacao',
        ),
    ]
